### ISSUE TITLE
Big project issue

### ISSUE THREAD

**Issue by axidex** [ntoskernel/deepsecrets#5]
Hello!

I'm stacked with problem that DS can't perform scanning on big projects, because it's interrupting on same file.

In k8s I see that CPU graph is growing to max and then scan is getting stuck.

How many resources do I need to scan projects with 100k - 1M line of code?

**Comment by ntoskernel** [comment]
Hi! Thanks for the report!
I'm aware of this problem and will fix it in the next releases.
Looks like we have to introduce some resource limitation techniques.

**Comment by ntoskernel** [comment]
Fixed in https://github.com/ntoskernel/deepsecrets/releases/tag/v1.2.0
